# -*- coding: utf-8 -*-
"""Project_Titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/thecodescholar/DA_Python_Jun_21/blob/main/Project_Titanic.ipynb

# Project_titanic
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

# %matplotlib inline

"""## Data Operations Task

#### Q. Import the Titianic Dataset and Display the Head of the Dataset
"""



df = pd.read_csv("https://raw.githubusercontent.com/thecodescholar/Da_Python_Jun_21/main/Dataset/titanicDataset.csv")

"""#### Q. Show the Statistics of dataframe"""

cart = pd.DataFrame(item)

cart

"""#### Q. Display last 3 columns"""

cart.index

"""#### Q. Show Unique values in Embarked"""

df = pd.read_csv("nan.csv")

"""## Visualization Task

#### Q. Draw histogram for Age, using Matplotlib
"""

# python_histogram.py

ages = [10,12,14,16,18,20]

bins = [10,15,20,25,30,35]

plt.hist(ages,bins=bins,edgecolor='black')

"""#### Q. Draw countplot for Sex, using Seaborn"""

seaborn.countplot(x,y)

"""#### Q. Make a Pie Chart of Corona Cases by taking numbers list as [500000, 1800000, 1200000] and labels list as ["Deaths", "Total Cases", "Cured"]"""

import numpy as np

Labels = ["Deaths","Total Cases","Cured"]

List = [500000,1800000,1200000]

Colors = ['yellow','red','green']

patches,texts = plt.pie(List,Colors=Colors,shadow=True,startangle=90)

plt.legend(patches,Labels,loc="best")

plt.axis('equal')

plt.tight_layout()

plt.show()

"""### Great Job

## All the Best

# THE CODE SCHOLAR
"""